### ISSUE TITLE
 Wrong display of products

### ISSUE THREAD

**Issue by TubaApollo** [sajjadh47/Woo-Products-Slider-Pro#1]
![grafik](https://user-images.githubusercontent.com/86665265/227800449-8daee526-05fe-4b62-819c-41916b886d68.png)
As you can see in this screenshot, the products are not displayed in the correct size. As long as I only show one product, the size is normal.

I am using blocksy as the theme and the latest wordpress version, I can provide a plugin list and more information if needed.

**Comment by sajjadh47** [comment]
This is perhaps your Theme is applying Flex/Other CSS to each element... can you check each li element styles!! and maybe provide website URL to check by my end!! Thanks

**Comment by TubaApollo** [comment]
Thank you for looking into this, i hopefully can setup an account for you tomorrow, so you can view the website

**Comment by TubaApollo** [comment]
Okay no need to create an account, i created a page for testing: https://www.apollo.moe/product-slider-test-page/. I am not really sure what i have to do to check the element styles, where and how can i check this?
